name: Testing CICD

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t testing .

      - name: Save Docker image to file
        run: docker save testing -o testing.tar

      - name: Archive Docker image file
        run: tar -czf testing.tar.gz testing.tar

      - name: Upload Docker image file
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: testing.tar.gz

      - name: Delete old artifacts
        run: |
          gh api -X GET repos/${{ github.repository }}/actions/artifacts --paginate > artifacts.json
          jq '.artifacts[] | select(.expired == false) | {id: .id, name: .name, created_at: .created_at}' artifacts.json > active_artifacts.json
          KEEP=5
          jq -r 'sort_by(.created_at) | .[:-env.KEEP] | .[].id' active_artifacts.json > artifacts_to_delete.txt
          while read ARTIFACT_ID; do
            echo "Deleting artifact ID: $ARTIFACT_ID"
            gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID
          done < artifacts_to_delete.txt

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download Docker image file
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: ~/

      - name: Extract Docker image file
        run: |
          mkdir -p extracted-image
          tar -xzf ~/testing.tar.gz -C extracted-image

      - name: Check contents of extracted-image
        run: ls -l extracted-image/

      - name: Set permissions for extracted-image
        run: chmod -R 755 extracted-image/
        
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "extracted-image/"
          target: "~/docker-image"
          timeout: 60s
          command_timeout: 20m

      - name: SSH to EC2 and load Docker image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd
