
name: Testing CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t chirag869/testing .
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: chirag869
          password: Chirag@123

      - name: Push Docker image to DockerHub
        run: docker push chirag869/testing
