
name: Testing CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t chirag869/testing .
        
      - name: Save Docker image to file
        run: docker save testing -o testing.tar

      - name: Archive Docker image file
        run: tar -czf testing.tar.gz testing.tar

      - name: Upload Docker image file
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: testing.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image file
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: testing.tar.gz

      - name: Extract Docker image file
        run: tar -xzf testing.tar.gz

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 3.109.184.166
          username: ubuntu
          key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBa2RyVmx5SHRFeUdzY21RWFNzd2hpVU45a1dkTlc5TkFtcWF4Z0djLzhTL0kwTGJtCktJWStjSE9naWRETzN1SjQvNnk3NEM3NTdEdi9rZlI4K3RHTUhiVVFBVGIxNFhxUm5adlBNZksyRzJ3YmJoSGwKVDVyTE9TSlIxbVdYa09EYzJBeDVMWWorOThmR213VzFKT25XMUlNSExPNjhoY2c2clFOdXgwUFRBVzJ2MGJvNgpDNDV2SFA0SUhYRU4weU9EWjZ4MHRYWkFCY2FQb3YrSHJ2WnVOM0ZTemZNNGJXSkZHbk9IQUVlRlpiK294MUd5CkNuVkt0NmlJNmVoRWZDNXFiUXZDdVF6U1lteE80K3BxLzdyZlQwNWd6bE8yaE1iUVpCTGVKOEZ5Ujc2TzE1Q24KOWVmZ3p2RE9wYnR1WWhxR3FSK3VPRHR0ckZDbDdobUo3b2hpSlFJREFRQUJBb0lCQURwTVFNRTJ3ejY1WCtjZApFSjVKOTBHWkkxQ0IvTTZ1SW8xdUFWYTBiajlsL1J0SGI3bFU1eElsZFU2QWtwOU40RlU1WXFMWncvVmppZVI1CjE1YWRPU2NLbndvTlFMeE9OSFBOdWtSWm9lWldFS1N2TEh2a0FFU203aFVHNkV6MVEvQnJFK2hhY0tielIvUGcKbFNYYS9ZNVZqUUd0cnRhK1VJMms2SnRuQmFqMDV5NVFBTURDeWNLWXpCdXNSMWN5MHhvN2JSMHNhM2lmQ1NDaQp1a214dVpJUnVhS1ljZjBPaFA5M091Znl4c1JiZEFmcHhTaWcyRUJwYWRqQlJXRE04QzFGNURrNkdwNkFESlV5CmZKY0ZjQjkxekgwaENxbXNhZ3g5Q1Bxa0xXSEdIVXdUZ3pIWnJNVFl4UXpwNXdEbEM1ZzhKK1JCMXllLzdmVHQKeDdlbDZjRUNnWUVBd3ZzUVJHbytQNFN6UEV6d2pkamNxVU9WQnJlMXhwamtNT0VTamN4RG1HdmZVR3FXcHc5MQprQStTdUVSY25Qc2EvRTFlOU41OGpHN2lxd2hlUGxMaGxhV0dsbkM3TFU1elR0SXZYbXA2NWVuZzdlZnY3aCtXCkZ3MWxyMFVxTWdXV2llMnltSy9LUHNzMENjN0NvaU0wZ1VaMWJLZzI0RnM2VGhxSWlYTy8wRlVDZ1lFQXY0QUoKRm4wZytsazk5UjZtMXJVRDBUQkE2WHdtRmhCMUY2N0lOaHlOdzV3anlMNmpxT0FmbW94bFJtYWtpOHhESGdZTApSeVFkUHdBRWE1WDI2WFV1NnFzam9BOTFEYXZIRnVmdzlWUVREb2F2Y2dmbnptMkxuVUNaU25LZkpiSS9BNWVqCjlSYS9mQ0ZCZzc3dVhIbTdDNFVnYUtGakF5NXhFVCtNbmdpUDJwRUNnWUE3SForNi9uTk5FdEM4OFo3bGd1QzAKT1JkUDZCY20xV2dxSWJOY1pwZi8rSVRHZnVxYVVDZVd2QUlCK0VnVUdGWUFOUDBiUlBHQ0tvUnkwcUN3U0xTNAppRzBiNDZYOGdKS1pUVVNyWGFGUlgrMmdjL2ZjdkpybTlscmtIeFpDQUV1NkdlVlNRY29SNjg0bFF4amp5OFM1CmhVRkk1bDlzK252Yy9sSnpTakxYMlFLQmdBeEl2a3gvQWxxTTF2aWVXcjF6SnllSUhPSGRZT1FSY2pGdXVORWYKeThnOGY5OGt1NExkdmFsQVVFN1B6c1pZK0FVNUJnZ3VQT0lKc2o3a2c4NCtBaUJ6a2ZsMmhGKzRJVEZLOTU0RgpJcVBQNS9rOG9KWVJXTjloZ1hQUkhueGdqc0pBTy9oQTJVK3hJbTY5RkxWQjZjbTNaSGpSd1hRMnluSDh6WnhsCm1EVEJBb0dCQU1IelpVaXloNDZtcXRRbk1Rb3ZJOGovZnh2U2lLN0FYRnd0L3pOTk1uNUtYTklaOWdiWkhET2wKOVlMc0V1QmFaQjFBdGQ1RFpIdTFiQUh5WkRLN2ViN3hsT3hja1NaYitvdG16KzZ6UmU5Vm1mcDZnK3ljQ1prQQp2Zm1SeTRUZzVlczVOemFKY0lObGJmeW9sOGJDMXFtSzN0Ri9BR3B5RzRsV2tWbVdNRE5XCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
          source: "testing.tar"
          target: "~/"

      - name: SSH to EC2 and load Docker image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 3.109.184.166
          username: ubuntu
          key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBa2RyVmx5SHRFeUdzY21RWFNzd2hpVU45a1dkTlc5TkFtcWF4Z0djLzhTL0kwTGJtCktJWStjSE9naWRETzN1SjQvNnk3NEM3NTdEdi9rZlI4K3RHTUhiVVFBVGIxNFhxUm5adlBNZksyRzJ3YmJoSGwKVDVyTE9TSlIxbVdYa09EYzJBeDVMWWorOThmR213VzFKT25XMUlNSExPNjhoY2c2clFOdXgwUFRBVzJ2MGJvNgpDNDV2SFA0SUhYRU4weU9EWjZ4MHRYWkFCY2FQb3YrSHJ2WnVOM0ZTemZNNGJXSkZHbk9IQUVlRlpiK294MUd5CkNuVkt0NmlJNmVoRWZDNXFiUXZDdVF6U1lteE80K3BxLzdyZlQwNWd6bE8yaE1iUVpCTGVKOEZ5Ujc2TzE1Q24KOWVmZ3p2RE9wYnR1WWhxR3FSK3VPRHR0ckZDbDdobUo3b2hpSlFJREFRQUJBb0lCQURwTVFNRTJ3ejY1WCtjZApFSjVKOTBHWkkxQ0IvTTZ1SW8xdUFWYTBiajlsL1J0SGI3bFU1eElsZFU2QWtwOU40RlU1WXFMWncvVmppZVI1CjE1YWRPU2NLbndvTlFMeE9OSFBOdWtSWm9lWldFS1N2TEh2a0FFU203aFVHNkV6MVEvQnJFK2hhY0tielIvUGcKbFNYYS9ZNVZqUUd0cnRhK1VJMms2SnRuQmFqMDV5NVFBTURDeWNLWXpCdXNSMWN5MHhvN2JSMHNhM2lmQ1NDaQp1a214dVpJUnVhS1ljZjBPaFA5M091Znl4c1JiZEFmcHhTaWcyRUJwYWRqQlJXRE04QzFGNURrNkdwNkFESlV5CmZKY0ZjQjkxekgwaENxbXNhZ3g5Q1Bxa0xXSEdIVXdUZ3pIWnJNVFl4UXpwNXdEbEM1ZzhKK1JCMXllLzdmVHQKeDdlbDZjRUNnWUVBd3ZzUVJHbytQNFN6UEV6d2pkamNxVU9WQnJlMXhwamtNT0VTamN4RG1HdmZVR3FXcHc5MQprQStTdUVSY25Qc2EvRTFlOU41OGpHN2lxd2hlUGxMaGxhV0dsbkM3TFU1elR0SXZYbXA2NWVuZzdlZnY3aCtXCkZ3MWxyMFVxTWdXV2llMnltSy9LUHNzMENjN0NvaU0wZ1VaMWJLZzI0RnM2VGhxSWlYTy8wRlVDZ1lFQXY0QUoKRm4wZytsazk5UjZtMXJVRDBUQkE2WHdtRmhCMUY2N0lOaHlOdzV3anlMNmpxT0FmbW94bFJtYWtpOHhESGdZTApSeVFkUHdBRWE1WDI2WFV1NnFzam9BOTFEYXZIRnVmdzlWUVREb2F2Y2dmbnptMkxuVUNaU25LZkpiSS9BNWVqCjlSYS9mQ0ZCZzc3dVhIbTdDNFVnYUtGakF5NXhFVCtNbmdpUDJwRUNnWUE3SForNi9uTk5FdEM4OFo3bGd1QzAKT1JkUDZCY20xV2dxSWJOY1pwZi8rSVRHZnVxYVVDZVd2QUlCK0VnVUdGWUFOUDBiUlBHQ0tvUnkwcUN3U0xTNAppRzBiNDZYOGdKS1pUVVNyWGFGUlgrMmdjL2ZjdkpybTlscmtIeFpDQUV1NkdlVlNRY29SNjg0bFF4amp5OFM1CmhVRkk1bDlzK252Yy9sSnpTakxYMlFLQmdBeEl2a3gvQWxxTTF2aWVXcjF6SnllSUhPSGRZT1FSY2pGdXVORWYKeThnOGY5OGt1NExkdmFsQVVFN1B6c1pZK0FVNUJnZ3VQT0lKc2o3a2c4NCtBaUJ6a2ZsMmhGKzRJVEZLOTU0RgpJcVBQNS9rOG9KWVJXTjloZ1hQUkhueGdqc0pBTy9oQTJVK3hJbTY5RkxWQjZjbTNaSGpSd1hRMnluSDh6WnhsCm1EVEJBb0dCQU1IelpVaXloNDZtcXRRbk1Rb3ZJOGovZnh2U2lLN0FYRnd0L3pOTk1uNUtYTklaOWdiWkhET2wKOVlMc0V1QmFaQjFBdGQ1RFpIdTFiQUh5WkRLN2ViN3hsT3hja1NaYitvdG16KzZ6UmU5Vm1mcDZnK3ljQ1prQQp2Zm1SeTRUZzVlczVOemFKY0lObGJmeW9sOGJDMXFtSzN0Ri9BR3B5RzRsV2tWbVdNRE5XCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
          port: 3000
          script: |
            docker load -i ~/testing.tar
            docker stop testing || true
            docker rm testing || true
            docker run -d --name testing -p 3000:3000 testing
